import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './components/Providers'
import { SignInButton } from './components/SignInButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header className="flex justify-end gap-4 bg-gradient-to-b from-white to-gray-200 shadow">
            <SignInButton />
          </header>

          {children}
        </Providers>
      </body>
    </html>
  )
}
